# Generated by Django 4.2.7 on 2023-11-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='timestamp',
        ),
    ]
